[motor_one_pin]
enable = 19
input_one = 23
input_two = 24

[motor_two_pin]
enable = 18
input_one = 20
input_two = 16

[ultrasonic_pin]
trigger = 17
echo = 27

[camera]
resolution_source_width = 1280
resolution_source_height = 720
resolution_target_width = 64
resolution_target_height = 64